// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: txn.proto

#include "txn.pb.h"

#include <algorithm>

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/wire_format_lite.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>

PROTOBUF_PRAGMA_INIT_SEG

namespace _pb = ::PROTOBUF_NAMESPACE_ID;
namespace _pbi = _pb::internal;

namespace txn {
PROTOBUF_CONSTEXPR Txn::Txn(
    ::_pbi::ConstantInitialized)
  : txn_id_(int64_t{0}){}
struct TxnDefaultTypeInternal {
  PROTOBUF_CONSTEXPR TxnDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~TxnDefaultTypeInternal() {}
  union {
    Txn _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 TxnDefaultTypeInternal _Txn_default_instance_;
}  // namespace txn
static ::_pb::Metadata file_level_metadata_txn_2eproto[1];
static constexpr ::_pb::EnumDescriptor const** file_level_enum_descriptors_txn_2eproto = nullptr;
static constexpr ::_pb::ServiceDescriptor const** file_level_service_descriptors_txn_2eproto = nullptr;

const uint32_t TableStruct_txn_2eproto::offsets[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::txn::Txn, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::txn::Txn, txn_id_),
};
static const ::_pbi::MigrationSchema schemas[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  { 0, -1, -1, sizeof(::txn::Txn)},
};

static const ::_pb::Message* const file_default_instances[] = {
  &::txn::_Txn_default_instance_._instance,
};

const char descriptor_table_protodef_txn_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) =
  "\n\ttxn.proto\022\003txn\"\025\n\003Txn\022\016\n\006txn_id\030\001 \001(\003b"
  "\006proto3"
  ;
static ::_pbi::once_flag descriptor_table_txn_2eproto_once;
const ::_pbi::DescriptorTable descriptor_table_txn_2eproto = {
    false, false, 47, descriptor_table_protodef_txn_2eproto,
    "txn.proto",
    &descriptor_table_txn_2eproto_once, nullptr, 0, 1,
    schemas, file_default_instances, TableStruct_txn_2eproto::offsets,
    file_level_metadata_txn_2eproto, file_level_enum_descriptors_txn_2eproto,
    file_level_service_descriptors_txn_2eproto,
};
PROTOBUF_ATTRIBUTE_WEAK const ::_pbi::DescriptorTable* descriptor_table_txn_2eproto_getter() {
  return &descriptor_table_txn_2eproto;
}

// Force running AddDescriptors() at dynamic initialization time.
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::_pbi::AddDescriptorsRunner dynamic_init_dummy_txn_2eproto(&descriptor_table_txn_2eproto);
namespace txn {

// ===================================================================

class Txn::_Internal {
 public:
};

Txn::Txn(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor();
  // @@protoc_insertion_point(arena_constructor:txn.Txn)
}
Txn::Txn(const Txn& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  txn_id_ = from.txn_id_;
  // @@protoc_insertion_point(copy_constructor:txn.Txn)
}

inline void Txn::SharedCtor() {
txn_id_ = int64_t{0};
}

Txn::~Txn() {
  // @@protoc_insertion_point(destructor:txn.Txn)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void Txn::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
}

void Txn::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}

void Txn::Clear() {
// @@protoc_insertion_point(message_clear_start:txn.Txn)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  txn_id_ = int64_t{0};
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* Txn::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // int64 txn_id = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 8)) {
          txn_id_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* Txn::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:txn.Txn)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // int64 txn_id = 1;
  if (this->_internal_txn_id() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteInt64ToArray(1, this->_internal_txn_id(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:txn.Txn)
  return target;
}

size_t Txn::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:txn.Txn)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // int64 txn_id = 1;
  if (this->_internal_txn_id() != 0) {
    total_size += ::_pbi::WireFormatLite::Int64SizePlusOne(this->_internal_txn_id());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData Txn::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSizeCheck,
    Txn::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*Txn::GetClassData() const { return &_class_data_; }

void Txn::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message* to,
                      const ::PROTOBUF_NAMESPACE_ID::Message& from) {
  static_cast<Txn *>(to)->MergeFrom(
      static_cast<const Txn &>(from));
}


void Txn::MergeFrom(const Txn& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:txn.Txn)
  GOOGLE_DCHECK_NE(&from, this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (from._internal_txn_id() != 0) {
    _internal_set_txn_id(from._internal_txn_id());
  }
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void Txn::CopyFrom(const Txn& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:txn.Txn)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool Txn::IsInitialized() const {
  return true;
}

void Txn::InternalSwap(Txn* other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(txn_id_, other->txn_id_);
}

::PROTOBUF_NAMESPACE_ID::Metadata Txn::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_txn_2eproto_getter, &descriptor_table_txn_2eproto_once,
      file_level_metadata_txn_2eproto[0]);
}

// @@protoc_insertion_point(namespace_scope)
}  // namespace txn
PROTOBUF_NAMESPACE_OPEN
template<> PROTOBUF_NOINLINE ::txn::Txn*
Arena::CreateMaybeMessage< ::txn::Txn >(Arena* arena) {
  return Arena::CreateMessageInternal< ::txn::Txn >(arena);
}
PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)
#include <google/protobuf/port_undef.inc>
